packages:
  - apps/*
  - packages/*
  - ui/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - better-sqlite3
  - classic-level
  - esbuild
  - maplibre-gl
  - shadcn-docs-nuxt
  - sharp
  - unrs-resolver
  - vue-demi
