import { getAppRouterAuthProps } from '@forgebase-ts/web-auth/frameworks/nextjs/app-router';
import './global.css';
import ClientAuthProvider from './providers/auth-provider';
import { DatabaseProvider } from './providers/database-provider';

export const metadata = {
  title: 'Welcome to test-web',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const authProps = getAppRouterAuthProps();
  return (
    <html lang="en">
      <body>
        <ClientAuthProvider
          initialUser={authProps.user}
          initialAccessToken={authProps.accessToken}
          initialRefreshToken={authProps.refreshToken}
        >
          <DatabaseProvider apiUrl="http://localhost:8000/api">
            {children}
          </DatabaseProvider>
        </ClientAuthProvider>
      </body>
    </html>
  );
}
