/**
 * This file was auto-generated by @forgebase/cli.
 * Do not modify this file manually.
 */

export interface Users {
  id: number;
  email: string;
  age: number | null;
  is_active: boolean;
  metadata: any | null;
  created_at: string;
}

export interface Posts {
  id: number;
  title: string;
  content: string | null;
  author_id: number;
}

export interface Schema {
  users: Users;
  posts: Posts;
}
